name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
      - uses: addnab/docker-run-action@v3
        with:
        #   username: ${{ secrets.DOCKER_USERNAME }}
        #   password: ${{ secrets.DOCKER_PASSWORD }}
        #   registry: gcr.io
          image: mxpv/podsync:latest
          options: -v ${{ github.workspace }}/config.toml:/app/config.toml -e ABC=123
        #   run: |
        #     echo "Running Script"
        #     /work/run-script
